addSbtPlugin("com.eed3si9n" % "sbt-dirty-money" % "0.1.0")
addSbtPlugin("com.eed3si9n" % "sbt-sh" % "0.1.0")
addSbtPlugin("com.github.alexarchambault" %% "sbt-ammonite" % "0.1.2")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.0")
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.14")
